# -*- coding: utf-8 -*-
"""state_preparation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ftQPAWOaK6C0OljB0oRmzqwyE9PWH7ke
"""

from pulser import Pulse, Sequence
from pulser.waveforms import BlackmanWaveform
import numpy as np

def pulse_from_statevector(state_coefficients):
  """|0> --- seq.add(pulse_from_statevector([alpha, beta]), channel_id) ---> alpha |0> + beta |1>"""

  amplitude=BlackmanWaveform(1000, 2 * np.arccos(state_coefficients[0])) 
  phase=np.angle(state_coefficients[1]) 
  detuning=0
  post_phase_shift=2 * phase + (np.pi /2) 

  pulse = Pulse.ConstantDetuning(
      amplitude=amplitude, detuning=detuning, phase=phase, post_phase_shift=post_phase_shift
      )

  return pulse
